name: Node.js
on:
  push:
    branches: main
  pull_request:
permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: "16"
      - run: |
          npm ci
          cp config/sample.ts config/config.ts
          npm run build
          npm test
